all:
  hosts:
    vmanage:
      ansible_host: 192.168.100.10
      ansible_user: admin
      ansible_password: admin
      vmanage_port: 8443
  vars:
    org_name: "SDWAN-LAB"
    vbond_address: "10.0.0.12"
